### ISSUE TITLE
How can i install this

### ISSUE THREAD

**Issue by middleJack** [vedi/restifizer-unity3d#4]
To install a plugin in Unity, I usually put a dll in Plugins folder and voilá. But UnityHTTP & restifizer-unity3d don't even make use of Releases section:
https://github.com/vedi/restifizer-unity3d/releases
https://github.com/andyburke/UnityHTTP/releases

And none of them have an install entry in their README.MD.

¿How can i install them? By throwing all their folders in /Plugins/ ?

**Comment by vedi** [comment]
@middleJack, at the moment it's supposed to work from sources. You can clone it with git, or add as git submodule to your projects sources, or use "Download ZIP" button in the Github.

**Comment by middleJack** [comment]
Another question, related to UnityHTTP dependency. It overwrites the default JSON class, which i'm using in my project. 
¿How can i force a file to use the default JSON class and not the imported by UnityHTTPD?

**Comment by vedi** [comment]
> It overwrites the default JSON class

do you mean you have the class with the same name and with the same functionality?

**Comment by middleJack** [comment]
Soz! I thought i was using Unity's default JSON class, but it's SimpleJSON so i can set the namespace! Thanks

Maybe you wanna take a look at: https://github.com/typicode/json-server
